name: Westonia
version: 'Beta 1.0 DEV_BUILD_MC1.21.1'
main: coffee.j4n.westonia.Westonia
api-version: 1.20
author: J4N

commands:
  fly:
    permission: westonia.commands.team.fly
    description: Fly like a bird!
